name: hs-bomb-party
version: 0.1.0.0
github: githubuser/hs-bomb-party
license: BSD-3-Clause
author: Author name here
maintainer: example@example.com
copyright: 2024 Author name here

extra-source-files:
  - README.md
  - CHANGELOG.md

  # Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/hs-bomb-party#readme>

dependencies:
  - aeson
  - aeson-qq
  - async
  - base >= 4.7 && < 5
  - binary
  - bytestring
  - conduit
  - containers
  - cookie
  - hashable
  - http-api-data
  - http-types
  - lucid
  - lucid-htmx
  - mtl
  - network-uri
  - nonempty-zipper
  - optics-core
  - optics-th
  - optics-extra
  - optics-operators
  - pretty-show
  - rapid
  - random
  - rio
  - servant-lucid
  - servant-server
  - servant-websockets
  - servant-htmx
  - shakespeare
  - stm
  - text
  - unordered-containers
  - uuid
  - wai
  - wai-websockets
  - warp
  - websockets

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DisambiguateRecordFields
  - EmptyCase
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTSyntax
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadComprehensions
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - ParallelListComp
  - PartialTypeSignatures
  - PatternSynonyms
  - RankNTypes
  - RecordWildCards
  - RecursiveDo
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators

library:
  source-dirs: src

executables:
  hs-bomb-party:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - hs-bomb-party

tests:
  hs-bomb-party-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - hs-bomb-party
      - hspec
      - hspec-wai
      - hspec-wai-json
      - aeson
